name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      project:
        description: "Project to deploy"
        required: true
        default: "project1-static-website"
        type: choice
        options:
          - project1-static-website
          - project2-serverless-api

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    
    strategy:
      matrix:
        project:
          - project1-static-website
          - project2-serverless-api

    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::127214156202:role/CloudPortfolioGitHubActionsRole
          aws-region: us-west-2

      - name: Confirm AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan

  terraform-apply:
    name: Manual Terraform Apply
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    defaults:
      run:
        working-directory: ${{ github.event.inputs.project }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::127214156202:role/CloudPortfolioGitHubActionsRole
          aws-region: us-west-2

      - name: Confirm AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve
    
      - name: Invalidate CloudFront cache
        if: ${{ github.event.inputs.project == 'project1-static-website' }}
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?DomainName=='d32097lzgag73x.cloudfront.net'].Id | [0]" --output text)
          aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"